---
title: "Pipeline"
author: "202310601"
date: "November 2 2023"
output: html_document
---

```{r setup, include=FALSE} 
# this chunk contains code that sets global options for the entire .Rmd. 
# we use include=FALSE to suppress it from the top of the document, but it will still appear in the appendix. 

knitr::opts_chunk$set(echo = FALSE) # actually set the global chunk options. 
# we set echo=FALSE to suppress code such that it by default does not appear throughout the document. 
# note: this is different from .Rmd default
```

### Exercise 1 
Here I will demonstrate the pipeline. 

```{r ex1.1, message = FALSE}
# Load in libraries:
library(dplyr)

# Define a function with a single argument data and perform a data transformation
transform_orange <- function(data){
  transform_data <- data %>%
  mutate(age_squared = age^2) # squaring the 'age' variable
  
  return(transform_data)
}

# Call the function with the 'Orange' dataset
transformed_orange_data <- transform_orange(Orange)
transformed_orange_data

```

```{r ex1.2}

# Add a second argument to the same function
transform_orange <- function(data, transformation_type = "age") {
  if (transformation_type == "age") {
    # Perform a data transformation on the 'age' variable
    transformed_data <- data %>%
      mutate(age = age^2)
  } else if (transformation_type == "circumference") {
    # Perform a data transformation on the 'circumference' variable (convert mm to inches)
    transformed_data <- data %>%
      mutate(circumference = circumference / 25.4)  
  }
  return(transformed_data)
}

```

## Appendix: All code in this assignment

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE} 
# this chunk generates the complete code appendix. 
# eval=FALSE tells R not to run (``evaluate'') the code here (it was already run before).
```
